DROP DATABASE IF EXISTS ssafydb;

CREATE DATABASE ssafydb DEFAULT CHARACTER SET utf8mb4;

USE ssafydb;

CREATE TABLE IF NOT EXISTS MOVIES(

id INTEGER AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(30) NOT NULL,
director VARCHAR(20) NOT NULL,
genre VARCHAR(20) NOT NULL,
runningtime INTEGER NOT NULL,
img VARCHAR(50),
orgimg VARCHAR(50)
);

DESC MOVIES;

SELECT * FROM MOVIES;

CREATE TABLE IF NOT EXISTS USER(
id VARCHAR(20) PRIMARY KEY,
name VARCHAR(10),
pass VARCHAR(20) NOT NULL
);

DESC USER;

INSERT INTO USER VALUES('ssafy', 'ssafy', 'ssafy');

SELECT * FROM USER;

